apiVersion: v1
kind: Pod
metadata:
  name: ex02c-pod
spec:
  containers:
  - name: ex02c-container
    image: registry.redhat.io/ubi8/nginx-120
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    volumeMounts:
    - name: wwwdata-volume
      mountPath: /opt/app-root/src
  volumes:
  - name: wwwdata-volume
    configMap:
      name: ex02c-config
      items:
      - key: "indexContent"
        path: "index.html"
