apiVersion: v1
kind: Pod
metadata:
  name: ex02d-pod
spec:
  containers:
  - name: ex02d-container
    image: registry.redhat.io/ubi8/nginx-120
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    volumeMounts:
    - name: wwwdata-volume
      mountPath: /opt/app-root/src
  volumes:
  - name: wwwdata-volume
    configMap:
      name: ex02d-config
