apiVersion: v1
kind: Pod
metadata:
  name: ex12-pod
spec:
  # restartPolicy: Never
  containers:
  - name: ex12-container
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.15
    command: ["/bin/sh"]
    args: ["-c", "sleep 5s; exit 42"]

