apiVersion: v1
kind: Pod
metadata:
  name: ex12-pod
spec:
  # restartPolicy: Never
  containers:
  - name: ex12-container
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.15
    command: ["/bin/sh"]
    args: ["-c", "date --rfc-3339=seconds; echo 'Sleeping ...'; sleep 5s; echo 'No good!'; exit 42"]

