apiVersion: v1
kind: Pod
metadata:
  name: ex02a-pod
spec:
  containers:
  - name: ex02a-container
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.12
    command: ["sleep"]
    args: ["4h"]
    env:
    - name: DEMO_HELLO
      valueFrom:
        configMapKeyRef:
          name: ex02a-config
          key: hello
