apiVersion: v1
kind: Pod
metadata:
  name: ex02b-pod
spec:
  containers:
  - name: ex02b-container
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.15
    command: ["sleep"]
    args: ["4h"]
    envFrom:
    - configMapRef:
        name: ex02b-config
