resources:
  - ../../base

labels:
  - pairs:
      stage: prod

patches:
  - path: deployment.yml
  - path: route.yml

configMapGenerator:
# A ConfigMap with one key, embedding a file
- name: ex15-wwwdata
  files:
  - index.html