resources:
- deployment.yml
- service.yml
- route.yml

configMapGenerator:

# A ConfigMap with multiple keys for setting environment variables
- name: ex15-env
  envs:
  - ex15.env
  literals:
  - PROVIDER=APA-Tech
  - ANSWER=42

# A ConfigMap with one key, embedding a properties file
- name: ex15-wwwdata
  files:
  - index.html


