apiVersion: v1
kind: Pod
metadata:
  name: ex01c-multi-container-pod
spec:

  containers:
  
  - name: ex01c-nginx-container
    image: registry.redhat.io/ubi8/nginx-120
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    volumeMounts:
    - mountPath: /opt/app-root/src
      name: wwwdata-volume

  - name: ex01c-tools-container
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.12
    command: ["sleep"]
    args: ["4h"]
    volumeMounts:
    - mountPath: /wwwdata
      name: wwwdata-volume

  volumes:
  - name: wwwdata-volume
    emptyDir:
      sizeLimit: 500Mi